CREATE PROCEDURE MULTIPLY AS
BEGIN
DECLARE @NUM1 INT;
DECLARE @NUM2 INT;
DECLARE @ANSWER INT;
SELECT @NUM1 = 2;
SELECT @NUM2 = 3;
SELECT @ANSWER = @NUM1 * @NUM2;
SELECT CONCAT('THE PRODUCT OF ', @NUM1, ' AND ', @NUM2, ' IS ', @ANSWER);  
END;